# How many outgoing links per class (edge IRIs)?

SELECT ?s ?class (count(?p) as ?nb_out_edges) WHERE {
  ?s rdf:type ?class .
  ?s ?p ?o .
}
GROUP BY ?s ?class
ORDER BY DESC (?nb_out_edges)
LIMIT 1000
