# Count of Types per Domain
## This query finds the number of instances of types per web domain

PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
SELECT ?domain ?type (COUNT(*) AS ?count) 
WHERE { 
    GRAPH ?g {
        ?s a ?type
    }
	?g pav:retrievedFrom ?o
    BIND (STRBEFORE(STRAFTER(STR(?o), "//"), "/") AS ?domain)
} 
GROUP BY ?domain ?type
ORDER BY DESC (?count)
