#+ summary: Number of domains
#+ description: This query finds the number of distinct web domains that data has been harvested from
#+ tags:
#+   - Data Statistics

PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
SELECT (COUNT(distinct ?domain) AS ?count)
WHERE {
	?s pav:retrievedFrom ?o
    BIND (REPLACE(STRAFTER(STR(?o), "//"), "/.*", "") AS ?domain)
}
