#+ summary: Number of Domain Feeds
#+ description: This query finds the number of domains imported through a DataFeed
#+ tags:
#+   - Data Statistics

PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
SELECT (COUNT(*) AS ?count)
WHERE {
	?s pav:retrievedFrom ?o ;
		a schema:DataFeed .
	BIND (REPLACE(STRAFTER(STR(?o), "//"), "/.*", "") AS ?domain)
}
