#+ summary: Harvested Pages per Domain
#+ description: This query finds the number of pages per web domain that was harvested
#+ tags:
#+   - Stats

PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
SELECT ?domain (COUNT(*) AS ?count)
WHERE {
	?s pav:retrievedFrom ?o
	FILTER NOT EXISTS { ?s a schema:DataFeed }
	BIND (REPLACE(STRAFTER(STR(?o), "//"), "/.*", "") AS ?domain)
}
GROUP BY ?domain
ORDER BY DESC (?count)
